name: "Create Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'HashTraveler@users.noreply.github.com'
      - name: Bump package.json version
        run: npm version ${{ inputs.version }}
      - name: Push version tag
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'HashTraveler@users.noreply.github.com'
          git push
      - name: Detach new branch
        run: |
          version = cat package.json | jq -r '.version'
          git checkout -b release/$version
          git push --set-upstream origin release/$version
