name: Create release tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: npm version ${{ inputs.version }}
      - name: Push version tag
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'HashTraveler@users.noreply.github.com'
          git push
      - name: Detach new branch
        run: |
          version = cat package.json | jq -r '.version'
          git checkout -b release/$version
          git push --set-upstream origin release/$version
