name: "Create Release"
run-name: "Create ${{ inputs.version }} release"
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bump-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
      - name: Bump package.json version
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version
          version=$(cat package.json | jq -r '.version')
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: package.json
          DESTINATION_BRANCH: main
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          TODAY=$( date -u '+%Y-%m-%d' )
          MESSAGE="Bump package.json to $VERSION"
          SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
          --field message="$MESSAGE" \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA"
          --field content=@<( base64 -i $FILE_TO_COMMIT ) \
  tag-and-release:
    runs-on: ubuntu-latest
    needs:
      - bump-package
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag the commit
        run: |
          version=$(cat package.json | jq -r '.version')
          git tag "v$version"
          git push --set-upstream origin main --tags
      - name: Create new release branch
        run: |
          version=$(cat package.json | jq -r '.version')
          git checkout -b "release/$version"
          git push --set-upstream origin "release/$version"
          echo "tag_name=v$version" >> $GITHUB_ENV
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(cat package.json | jq -r '.version')
          gh release create "v$version" \
              --draft \
              --title="v$version" \
              --generate-notes
